### ISSUE TITLE
YAML metadata parsing failures with multi-paragraph values

### ISSUE THREAD

**Issue by VulpineAmethyst** [mkende/pmarkdown#6]
The YAML parsing silently bails on multi-paragraph blocks if the lines between them lack indentation; for example:

```yaml
title: some title
notes: |
    This is a paragraph

    This is another paragraph.
```

If indentation is present, however, `$yaml->{notes]` omits the blank lines, resulting in output like so:

```
This is a paragraph.
This is another paragraph.
```

This means that if I use Markdown inside such a block, I need to add the blank lines back before I pass it to `convert()`.

There are several modules in CPAN for parsing YAML, e.g. [YAML::PP](https://metacpan.org/pod/YAML::PP), which behave as expected and which support parsing from a string.
